callbacks:
  grad_norm_monitor:
    sub_module:
    - generator
    - discriminator
    - decoder
  model_checkpoint:
    every_n_train_steps: 1000
ckpt_path: checkpoints/vqgan-v1.pth
data:
  _target_: fish_speech.datasets.vqgan.VQGANDataModule
  batch_size: 6
  num_workers: 4
  train_dataset: ${train_dataset}
  val_batch_size: 4
  val_dataset: ${val_dataset}
defaults:
- base
- _self_
hop_length: 256
model:
  _target_: fish_speech.models.vqgan.VQGAN
  decoder:
    _target_: fish_speech.models.vqgan.modules.modules.WN
    dilation_rate: 2
    hidden_channels: 256
    kernel_size: 3
    n_layers: 6
    out_channels: ${num_mels}
  discriminator:
    _target_: fish_speech.models.vqgan.modules.discriminator.EnsembleDiscriminator
  downsample:
    _target_: fish_speech.models.vqgan.modules.encoders.ConvDownSampler
    dims:
    - ${num_mels}
    - 512
    - 256
    kernel_sizes:
    - 3
    - 3
    strides:
    - 2
    - 2
  generator:
    _target_: fish_speech.models.vqgan.modules.decoder.Generator
    initial_channel: ${num_mels}
    resblock: '1'
    resblock_dilation_sizes:
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    - - 1
      - 3
      - 5
    resblock_kernel_sizes:
    - 3
    - 7
    - 11
    upsample_initial_channel: 512
    upsample_kernel_sizes:
    - 16
    - 16
    - 4
    - 4
    upsample_rates:
    - 8
    - 8
    - 2
    - 2
  hop_length: ${hop_length}
  lr_scheduler:
    _partial_: true
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.999999
  mel_encoder:
    _target_: fish_speech.models.vqgan.modules.modules.WN
    dilation_rate: 2
    hidden_channels: 256
    kernel_size: 3
    n_layers: 6
  mel_transform:
    _target_: fish_speech.models.vqgan.spectrogram.LogMelSpectrogram
    f_max: 8000
    f_min: 0
    hop_length: ${hop_length}
    n_fft: ${n_fft}
    n_mels: ${num_mels}
    sample_rate: ${sample_rate}
    win_length: ${win_length}
  mode: finetune
  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
    betas:
    - 0.8
    - 0.99
    eps: 1e-5
    lr: 2.0e-05
  sample_rate: ${sample_rate}
  segment_size: 8192
  vq_encoder:
    _target_: fish_speech.models.vqgan.modules.encoders.VQEncoder
    codebook_groups: 4
    codebook_size: 160
    downsample: 1
    in_channels: 256
    threshold_ema_dead_code: 0
    vq_channels: 256
n_fft: 1024
num_mels: 80
project: vqgan_finetune
resume_weights_only: true
sample_rate: 22050
segment_size: 256
train_dataset:
  _target_: fish_speech.datasets.vqgan.VQGANDataset
  filelist: data/demo/vq_train_filelist.txt
  hop_length: ${hop_length}
  sample_rate: ${sample_rate}
  slice_frames: ${segment_size}
trainer:
  accelerator: gpu
  devices: auto
  max_steps: 2000
  precision: '32'
  strategy: ddp_find_unused_parameters_true
  val_check_interval: 1000
val_dataset:
  _target_: fish_speech.datasets.vqgan.VQGANDataset
  filelist: data/demo/vq_val_filelist.txt
  hop_length: ${hop_length}
  sample_rate: ${sample_rate}
win_length: 1024
